# Project: megasena
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main_megasena.o
LINKOBJ  = main_megasena.o
LIBS     = -L"C:/development/Dev-Cpp/MinGW64/lib" -L"C:/development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/development/Dev-Cpp/MinGW64/include" -I"C:/development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/development/Dev-Cpp/MinGW64/include" -I"C:/development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = megasena.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main_megasena.o: main_megasena.c
	$(CC) -c main_megasena.c -o main_megasena.o $(CFLAGS)
